#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define ANALYZER_OPE_MODE_EL "EL"
#define ANALYZER_OPE_MODE_CF "CF"

#define ANALYZER_OPE_MODE ANALYZER_OPE_MODE_EL

#define ANALYZER_SERIAL_NO "DMMY012300"
#define ANALYZER_NAME "dahulk" //Also used as wifi SSID
#define ANALYZER_DEF_PSK "12345678"
#define ANALYZER_MDNS_SNAME "sp44xx"
#define ANALYZER_TCP_PORT 1717

#define DUMMY_BARCODE_SINGLE "single"
#define DUMMY_BARCODE_MULTI "multi-"
#define DUMMY_BARCODE_EL "el--"

#define DUMMY_LED_R 255
#define DUMMY_LED_G 0
#define DUMMY_LED_B 0

#define MESSAGE_ENQ 0x05
#define MESSAGE_ACK 0x06
#define MESSAGE_NAK 0x21

#define MESSAGE_OPCODE_GET_STATUS 0x10
#define MESSAGE_OPCODE_STATUS_CHG_NTC 0x11
#define MESSAGE_OPCODE_GET_SYSTEM_INFO 0x12
#define MESSAGE_OPCODE_ADJUST_PARAM_READING 0x13
#define MESSAGE_OPCODE_GET_PARAM_READING 0x14
#define MESSAGE_OPCODE_GET_PARAM_INITIALIZING 0x16
#define MESSAGE_OPCODE_MEASINFO_NTC 0x17
#define MESSAGE_OPCODE_SYSTEMLOG_NTC 0x19
#define MESSAGE_OPCODE_COMPL_NTC 0x1D

#define MESSAGE_OPCODE_SETUP_MEAS 0x20
#define MESSAGE_OPCODE_BARCODE_NTC 0x22
#define MESSAGE_OPCODE_ERROR_NTC 0x23
#define MESSAGE_OPCODE_END_MEAS 0x29
#define MESSAGE_OPCODE_TIPCASE_NTC 0x25

#define MESSAGE_OPCODE_START_MEAS 0x30
#define MESSAGE_OPCODE_STOP_MEAS 0x31
#define MESSAGE_OPCODE_STAT_MEAS 0x32
#define MESSAGE_OPCODE_COVER_OP 0x33
#define MESSAGE_OPCODE_SHUTDOWN 0x34
#define MESSAGE_OPCODE_MENU_OP 0x36
#define MESSAGE_OPCODE_ADJ_OP 0x3B

//#define MESSAGE_OPCODE_MENU_OP 0xA1

#define MESSAGE_OPCODE_MEAS_RESULT 0x40
#define MESSAGE_OPCODE_MEAS_IMAGE 0x41
#define MESSAGE_OPCODE_RES_EDIT 0x43
#define MESSAGE_OPCODE_CHK_RESULT 0x42
#define MESSAGE_OPCODE_ADJ_INFO 0x45


#define MESSAGE_OPCODE_GET_ERR_INFO 0x80
#define MESSAGE_OPCODE_ERR_NTC 0x81

#define MESSAGE_OPCODE_MEAS_TIME_NTC 0x91
#define MESSAGE_OPCODE_GET_MEAS_TIME 0x90

#define MESSAGE_OPCODE_GET_REAGENT_INFO_LIST 0xA0
#define MESSAGE_OPCODE_GET_REAGENT_INFO 0xA1
//#define MESSAGE_OPCODE_GET_REAGENT_INFO 0x36
#define MESSAGE_OPCODE_REAGENT_INFO_REQ_A 0xA2
#define MESSAGE_OPCODE_REAGENT_INFO_REQ_B 0xA3
#define MESSAGE_OPCODE_REAGENT_INFO_NTC 0xA4

#define MESSAGE_OPCODE_DUMMY 0xFF

#define MESSAGE_ERR_READ_NO_DATA -1
#define MESSAGE_ERR_READ_UNEXPECTED_EOM -2
#define MESSAGE_ERR_READ_INVALID_FORM -3

#define STATE_WARMING_UP 0x10
#define STATE_STANDBY 0x20
#define STATE_WAITING_FOR_RACK 0x30
#define STATE_MEASURING 0x40
#define STATE_INITIALIZING 0x50
#define STATE_END_PROCESSING 0x60
#define STATE_STOPPING 0x80
#define STATE_MEAS_STOPPED 0x90


#define STATE_BOOTPROGRAM_RUN 0
#define STATE_STARTING_UP 1
#define STATE_BOOT_COMPLETE 2
#define STATE_REWRITING_SUB_CPU 3
//#define STATE_STANDBY 4
//#define STATE_MEASURING 5
//#define STATE_END_PROCESSING 6
#define STATE_MEAS_INTERRUPTED 7
#define STATE_STOP_RESUME_YES 8
#define STATE_STOP_RESUME_NO 9
#define STATE_INTERRUPT_RESUME 10
#define STATE_ERROR_RELEASE 11
#define STATE_OTHERS 12


#define MESSAGE_WAITING 0
#define MESSAGE_NO_RACK 1
#define MESSAGE_MEASURING 2
#define MESSAGE_STATRESERVED 3
#define MESSAGE_ERRORMEASUREMENT 4
#define MESSAGE_PLEASEWAIT 5
#define MESSAGE_MEASUREFINISH 6
#define MESSAGE_STOPPING 7
#define MESSAGE_MEASUREMENTINTERRUPTED 8
#define MESSAGE_MEASUREMENTABORTED 9
#define MESSAGE_MEASUREMENTINTERRUPT 10

#define ICON_NO_SETTINGS -1
#define ICON_DISCONNECTED 0
#define ICON_CONNECTED 1

#define REAGENT_SINGLE_BASIC 0x00
#define REAGENT_SINGLE_LOT 0x01
#define REAGENT_MULTI_BASIC 0x02
#define REAGENT_MULTI_LOT 0x03
#define REAGENT_EL_BASIC 0x04
#define REAGENT_EPLATE_BASIC 0x05
#define REAGENT_EPLATE_LOT 0x06

#define COVER_STATE_CLOSE 0
#define COVER_STATE_OPEN 1
#define COVER_STATE_OPEN_MAINTE 2

#define COMPLETION_ERROR 0
#define COMPLETION_NORMAL 1

#define ABNORMAL_STATUS_NORMAL ""
#define ABNORMAL_STATUS_LESS_REF "L"
#define ABNORMAL_STATUS_GRTR_REF "H"
#define ABNORMAL_STATUS_LESS_MES "<"
#define ABNORMAL_STATUS_GRTR_MES ">"
#define ABNORMAL_STATUS_POOR_SPOT "?"
#define ABNORMAL_STATUS_EXPR_REAG "!"
#define ABNORMAL_STATUS_UNMEASURABLE "X"

#define TICK_STATE_NO 0
#define BG_PROC_STATE_NO 1
#define MAIN_STATE_NO 2

#define MENU_MODE_0		"0"
#define MENU_MODE_1		"1"
#define MENU_MODE_2		"2"
#define MENU_MODE_3		"3"
#define MENU_MODE_4		"4"
#define MENU_MODE_5		"5"
#define MENU_MODE_6		"6"
#define MENU_MODE_7		"7"
#define MENU_MODE_8		"8"
#define MENU_MODE_9		"9"
#define MENU_MODE_10	"10"
#define MENU_MODE_11	"11"
#define MENU_MODE_12	"12"
#define MENU_MODE_13	"13"
#define MENU_MODE_14	"14"
#define MENU_MODE_15	"15"
#define MENU_MODE_16	"16"
#define MENU_MODE_17	"17"
#define MENU_MODE_18	"18"
#define MENU_MODE_19	"19"
#define MENU_MODE_20	"20"
#define MENU_MODE_21	"21"
#define MENU_MODE_22	"22"
#define MENU_MODE_23	"23"
#define MENU_MODE_24	"24"
#define MENU_MODE_25	"25"
#define MENU_MODE_26	"26"

#define RM_MSG_NO_SEND 0
#define RM_MSG_NO_RECV 1

#define CALB_STATE_INIT 0
#define CALB_STATE_MEASURING 1
#define CALB_STATE_STOPPING 2


#define RESULT_FAIL 0
#define RESULT_OK 1

#define INIT_PROCESS 0
#define MENU_PROCESS 1
#define SHUTDOWN_PROCESS 2




#endif // #ifndef CONSTANTS_H_INCLUDED
